Fixed the bug that command parsing -f is str
In the command nnUNetv2_export_model_to_zip -f 2, it will parse 2 as str, making it unrecognizable. 

error: 
expected_fold_folder = ["fold_%d" % i if i != 'all' else 'fold_all' for i in folds]
TypeError: %d format: a number is required, not str